### ISSUE TITLE
__46-[CleverPushPlugin setLogListener:withResult:]_block_invoke: NSInternalInconsistencyException - Sending a message before the FlutterEngine has been run.

### ISSUE THREAD

**Issue by neronovs** [cleverpush/cleverpush-flutter-sdk#58] opened 2024-06-05 07:35 UTC
The issue is appeared in the Firebase Crashlytics:

__46-[CleverPushPlugin setLogListener:withResult:]_block_invoke

NSInternalInconsistencyException - Sending a message before the FlutterEngine has been run.

Stacktrace:
      Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x83f20 __exceptionPreprocess
1  libobjc.A.dylib                0x16018 objc_exception_throw
2  Foundation                     0x6de868 _userInfoForFileAndLine
3  Flutter                        0x1ba80 (Missing UUID 4c4c44bd55553144a1714204dc08bdb2)
4  Flutter                        0x5bf6a4 (Missing UUID 4c4c44bd55553144a1714204dc08bdb2)
5  Flutter                        0x5bff88 (Missing UUID 4c4c44bd55553144a1714204dc08bdb2)
6  Runner                         0x9fd450 __46-[CleverPushPlugin setLogListener:withResult:]_block_invoke + 394 (CleverPushPlugin.m:394)
7  CleverPush                     0x4decc (Missing UUID c5abf6f0dab537c1974d0b073d5705d7)
8  CleverPush                     0x4e00c (Missing UUID c5abf6f0dab537c1974d0b073d5705d7)
9  CleverPush                     0x3cd2c (Missing UUID c5abf6f0dab537c1974d0b073d5705d7)
10 CleverPush                     0x3d0f0 (Missing UUID c5abf6f0dab537c1974d0b073d5705d7)
11 libdispatch.dylib              0x213c _dispatch_call_block_and_release
12 libdispatch.dylib              0x3dd4 _dispatch_client_callout
13 libdispatch.dylib              0xb400 _dispatch_lane_serial_drain
14 libdispatch.dylib              0xbf64 _dispatch_lane_invoke
15 libdispatch.dylib              0x16cb4 _dispatch_root_queue_drain_deferred_wlh
16 libdispatch.dylib              0x16528 _dispatch_workloop_worker_thread
17 libsystem_pthread.dylib        0x4934 _pthread_wqthread
18 libsystem_pthread.dylib        0x10cc start_wqthread

**Comment by gbhrdt** [comment] 2024-06-05 11:57
Hi @neronovs can you confirm that you are using `setLogListener` right now? When are you calling this method?

**Comment by neronovs** [comment] 2024-06-05 14:01
No, are not. It looks like this method is called somewhere from the deep of the library.

**Comment by gbhrdt** [comment] 2024-06-26 13:28
@neronovs sorry for my delayed feedback. Would you be able to share a minimal reproduction project maybe? We are unable to replicate this issue on our side right now.

**Comment by gbhrdt** [comment] 2024-10-31 20:17
Closing due to no feedback for now. Feel free to ping me and I'll reopen it.

**Closed by gbhrdt** 2024-10-31 20:17 UTC
